#+TITLE: My emacs doom configuration
#+AUTHOR: Cody Goodman
#+EMAIL: cody@codygman.dev
#+LANGUAGE: en
#+STARTUP: inlineimages
#+PROPERTY: header-args :cache yes :results silent :padline no

* A Note On The Structure Of This Document
This document attempts to motivate changes first by describing a workflow in
prose and presenting examples inline or linking to headings such as [[id:a09cbdef-c018-45ff-af40-bdd78c0d7edd][Make Org
Agenda look nicer]] when appropriate.

Perhaps it's always appropriate  to have a workflow description and then link to
the relevant hierarchical [[id:bc892078-e21e-4f4e-885c-44c0ade78420][Configuration]] tree section, but for now I'm going
with the mixed approach since [[https://github.com/alhassy/emacs.d/blob/master/README.org#a-life-configuring-emacs][that style can be very nice]].
* Managing Life With Org Mode
** Capturing
*** Ideas
:PROPERTIES:
:ID:       783fc72a-92d9-4ee1-9d58-9e77486cc544
:END:
Any idea or note that comes to me throughout the day can be captured with a
simple capture template:

#+begin_src emacs-lisp :noweb-ref simple-todo-capture-template :tangle no :noweb yes
("t" "Todo (no clock in)" entry (file+headline "~/bsab/misc.org" "Misc")
             "* TODO %?
<<default-capture-properties>>
" :prepend t)
#+end_src

I find it's a good idea to prepend these tasks by default so your freshest ideas
are near the top of the file. Perhaps that's a bad habit or reinforces not
curating or refiling things enough though.
*** Oh Crap I Need To Drop Everything And Do X

Example: Stop configuring org for hours on end and clock in to "Go get dinner" :)

#+begin_src emacs-lisp :noweb-ref simple-todo-clocking-capture-template :tangle no :noweb yes
("T" "Todo" entry (file+headline "~/bsab/misc.org" "Misc")
             "* TODO %?
<<default-capture-properties>>
" :prepend t :clock-in t :clock-resume t)
#+end_src
*** Notes in existing projects
Just now I needed to capture the note:

"I like doom over my vanilla config because of the reload infrastructure and
benchmarking/timing information that is prevalent"

I wanted to be able to just capture it, but instead had to navigate to
=projects.org=, go to =Active Projects=, go to =try out doom emacs for possible
time savings=, find =notes on doom use through the week=.

Instead I'd like an =Note In Active Project= capture template where I could just
=SPC X a= (or using ivy to select that capture template text), type my note, and
then refile into any realistic level within =Projects.org -> Active Projects=
*** Projects
Projects may be created by from [[id:783fc72a-92d9-4ee1-9d58-9e77486cc544][Ideas/Notes]] I quickly captured

#+begin_src emacs-lisp :noweb-ref project-capture-template :tangle no :noweb yes
("p" "Project" entry (file+headline "~/bsab/projects.org" "Projects")
 (file "capture-templates/project-capture-template.org") :prepend t)
#+end_src

#+name: test
#+begin_src org :tangle ~/bsab/capture-templates/project-capture-template.org :mkdirp yes :noweb yes
,* TODO %? [/]
  <<default-capture-properties>>
,** TODO <1m project notes                  :plan:
         :PROPERTIES:
         :Effort:       00:01
         :END:
,** TODO plan project :plan:
,** TODO project good/bad recap
#+end_src
*** Additions To Default Capture
**** TODO Screenshots: Quickly record information
:PROPERTIES:
:ID:       b02315a9-91db-4a3a-a7d2-c9dadfec5f87
:END:
not working in doom and really missing them

see [[id:41a15340-e9ab-4722-88ea-5774020a5418][org-download]]

NOTE: Default doom attach directory is ~/org/attach which isn't synced with phone
***** TODO view screenshots across devices (PC/Android Orgzly)
**** TODO clock in/out smartly on state change
*** Linking To Relevant Information During Capture Or Notes
**** Linking to recent git commits
***** TODO store all recent magit commits with org-store-link
****** example
I notice that =cw= is slower in my org files in doom emacs than in my vanilla
config and note that down, I call =org-insert-link= and find the most recent
commit to the relevant doom emacs config project.
** Agenda: What should you be doing now?
The org agenda is quite a nice way to surface your notes into an actionable list
of priorities and scheduled items. Though we need to do some work to [[id:a09cbdef-c018-45ff-af40-bdd78c0d7edd][Make Org
Agenda look nicer]], it's well worth the effort.
** Viewing Org Files (prefer using agenda if possible)
*** Additions To Default Org Mode View
**** TODO hide properties by default
** Resources
*** https://github.com/alhassy/emacs.d/blob/master/README.org
* Configuration
:PROPERTIES:
:ID:       bc892078-e21e-4f4e-885c-44c0ade78420
:END:
** Personal Information
:PROPERTIES:
:header-args: :noweb-ref personal-info
:END:
*** Set full name
#+BEGIN_SRC emacs-lisp :tangle yes
(setq user-full-name "Cody Goodman")
#+END_SRC
*** Set email address
#+BEGIN_SRC emacs-lisp :tangle yes
(setq user-mail-address "cody@codygman.dev")
#+END_SRC
** Doom Core
Here I setup my config for the =doom-emacs= [[doom:core/][core]]
*** [[doom:core/core.el][Core]]
**** Use =jf= instead of default doom =jk=
#+BEGIN_SRC emacs-lisp :tangle yes
(setq-default evil-escape-key-sequence "jf")
#+END_SRC
**** disable line numbers
#+begin_src emacs-lisp :tangle yes
(setq display-line-numbers-type nil)
#+end_src
** Doom Visual
*** font
#+begin_src emacs-lisp :tangle yes
(setq doom-font (font-spec :family "Source Code Pro" :size 17))
#+end_src
** Org Mode
*** start after org macro
#+begin_src emacs-lisp :tangle yes
(after! org
#+end_src
*** Enable linking with org uuid
#+begin_src emacs-lisp :tangle yes
(require 'org-id)
(setq org-id-link-to-org-use-id t)
#+end_src
*** org capture templates
#+begin_src emacs-lisp :tangle yes :noweb yes
(setq org-capture-templates
      '(
<<simple-todo-capture-template>>
<<project-capture-template>>
<<simple-todo-clocking-capture-template>>
        ))
#+end_src
*** default org capture heading properties
#+name: default-capture-properties
#+begin_src text
:PROPERTIES:
:ID:       %(org-id-uuid)
:CREATED: %U
:END:
#+end_src
*** basics
**** Here is where my org files live
#+begin_src emacs-lisp
(setq org-directory "~/bsab")
(setq org-agenda-files '("~/bsab"))
#+end_src
**** These are my todo states
#+name: set-org-todo-keywords
#+begin_src emacs-lisp
  (setq org-todo-keywords
        '((sequence "TODO(t)" "STRT(s)" "IN-PROGRESS(i)" "NEXT(n)" "WAIT(w@/!)" "|" "DONE(d!)" "KILL(k@)")))
#+end_src
*** org agenda
**** Use Org Super Agenda
#+begin_src emacs-lisp :tangle yes
(setq org-super-agenda-header-map (make-sparse-keymap)) ;; don't break evil on org-super-agenda headings, see https://github.com/alphapapa/org-super-agenda/issues/50
(org-super-agenda-mode t)
(after! org-agenda (setq org-agenda-custom-commands
                         '(("d" "Dashboard"
                            (
                             (agenda ""
                              (
                               (org-agenda-overriding-header "Dashboard")
                               (org-agenda-span 'day)
                               (org-agenda-start-day (org-today))
                               (org-agenda-current-span 'day)
                               (org-super-agenda-groups
                                '(
                                  (:habit t :order 2)
                                  (:name "Schedule" :time-grid t :order 3)
                                  (:name "Scheduled Earlier"
                                         :scheduled past
                                         :order 10
                                         )
                                  (:name "Must Do Today"
                                         :and (:deadline today :priority "A")
                                         :deadline today
                                         :and (:deadline past :priority "A")
                                         :and (:scheduled t :priority "A")
                                         :and (:scheduled past :priority "A")
                                         :deadline past
                                         :order 1
                                         )
                                  (:name "Daily 10m Review"
                                         :regexp "daily 10m review"
                                         :and (:habit t :regexp "daily 10m review")
                                         :order 0
                                         )
                                  (:log t)

                                  ))))

                             )))))
#+end_src
**** Make Org Agenda look nicer
:PROPERTIES:
:ID:       a09cbdef-c018-45ff-af40-bdd78c0d7edd
:END:
***** remove =Scheduled: = text in front of org agenda items
It just takes up valuable space and doesn't have a use
#+begin_src emacs-lisp
(setq org-agenda-scheduled-leaders '("" ""))
#+end_src
*** end after org macro
#+begin_src emacs-lisp
)
#+end_src
